### ISSUE TITLE
add a readme

### ISSUE THREAD

**Issue by ORESoftware** [hidekiy/cors-cookie-test#1]
Hi there

Could you add a readme to this project to describe what it is trying to demonstrate?
I saw your article online and things look promising..but can't glean any useful info just yet..

my question is how to send a cookie from the browser to the server in a CORS request.

storing session data as a cookie seems more secure than anything else, but I am not sure how to send the front-end cookie in a CORS AJAX request...

thanks

**Comment by hidekiy** [comment]
I added a readme.
This app is a sample application that use cross domain cookie feature.

**Comment by hidekiy** [comment]
78b4a388887dab540c569e309210cedf070afd26
